# Generated by Django 3.0.5 on 2020-05-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200429_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
