# Generated by Django 3.0.5 on 2020-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_guestuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
